In [14]:
from tensorflow.keras.preprocessing.text import one_hot

In [15]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [16]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [17]:
voc_size=10000

In [20]:
onehot_reps=[one_hot(words,voc_size)for words in sent]
print(onehot_reps)

[[2741, 7821, 7591, 7909], [2741, 7821, 7591, 2130], [2741, 6563, 7591, 2674], [4355, 5878, 6539, 3311, 6970], [4355, 5878, 6539, 3311, 9085], [5548, 2741, 1446, 7591, 6075], [349, 8931, 5381, 3311]]


## Word Embedding Representation

In [21]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [22]:
import numpy as np

In [25]:
sent_len=8
embedded_docs=pad_sequences(onehot_reps,padding="pre",maxlen=sent_len)
print(embedded_docs)

[[   0    0    0    0 2741 7821 7591 7909]
 [   0    0    0    0 2741 7821 7591 2130]
 [   0    0    0    0 2741 6563 7591 2674]
 [   0    0    0 4355 5878 6539 3311 6970]
 [   0    0    0 4355 5878 6539 3311 9085]
 [   0    0    0 5548 2741 1446 7591 6075]
 [   0    0    0    0  349 8931 5381 3311]]


In [29]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_len))
model.compile("adam","mse")

In [30]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [31]:
print(model.predict(embedded_docs))

[[[ 0.04613174 -0.01648209  0.02144751  0.03899593  0.01198279
   -0.02680291  0.02645056  0.02522207 -0.04303671  0.04992049]
  [ 0.04613174 -0.01648209  0.02144751  0.03899593  0.01198279
   -0.02680291  0.02645056  0.02522207 -0.04303671  0.04992049]
  [ 0.04613174 -0.01648209  0.02144751  0.03899593  0.01198279
   -0.02680291  0.02645056  0.02522207 -0.04303671  0.04992049]
  [ 0.04613174 -0.01648209  0.02144751  0.03899593  0.01198279
   -0.02680291  0.02645056  0.02522207 -0.04303671  0.04992049]
  [ 0.00061866 -0.01304919  0.04613941 -0.03644617 -0.00643323
   -0.04512086  0.01291938  0.03315219 -0.02509198 -0.01622472]
  [ 0.0004706   0.03470427  0.02606497 -0.0226649  -0.01617919
    0.04338961 -0.03382897 -0.03717206  0.0164648  -0.04573804]
  [-0.04859276  0.002964    0.02702538  0.01676431  0.03567014
    0.02282052 -0.02955738  0.03726539 -0.0117209  -0.01691664]
  [-0.01418155  0.00980211  0.04757747 -0.0382818  -0.01331095
   -0.0326704   0.04300941 -0.04483484 -0.006602

In [32]:
print(embedded_docs[0])

[   0    0    0    0 2741 7821 7591 7909]
